---
title: "Análise sobre a Remuneração"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    #theme: bootstrap
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(echarts4r)
#alterar projeto

df_total <- readr::read_rds("~/Trabalho/CGINF/Projetos_R/coeficiente_de_Gini/data/df_total.rds")
df_orgao <- readr::read_rds("~/Trabalho/CGINF/Projetos_R/coeficiente_de_Gini/data/df_orgao.rds")
```

Visão geral
==============================================================

Row
-----------------------------------------------------------------------
### Remuneração

```{r}

# definir a ordem de SG_ORGAO_VINCULACAO pelo gini_index

orgaos <- df_orgao |>
  select(SG_ORGAO_VINCULACAO, gini_index) |> arrange(desc(gini_index)) |>
  distinct(SG_ORGAO_VINCULACAO) |> pull()

plot <- df_orgao |>
  mutate(SG_ORGAO_VINCULACAO = factor(SG_ORGAO_VINCULACAO, levels = orgaos)) |>
  group_by(SG_ORGAO_VINCULACAO) |>
  e_charts() |>
  e_boxplot(REMU_TOTAL) |>
  e_y_axis(
    axisLabel = list(
      formatter = htmlwidgets::JS(
        "function (value) { return 'R$ ' + value.toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0}); }"
      )
    )
  )|>
  e_x_axis(
    axisLabel = list(
      interval = 0,
      rotate = 45
    )
  ) |>
 e_tooltip(
    trigger = "item",
   formatter = htmlwidgets::JS(
     "function(params) {
        var group = params.name;
        var minimo = 'Mínimo: R$ ' + params.value[1].toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0});
        var q1 = 'Q1: R$ ' + params.value[2].toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0});
        var mediana = 'Mediana: R$ ' + params.value[3].toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0});
        var q3 = 'Q3: R$ ' + params.value[4].toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0});
        var maximo = 'Máximo: R$ ' + params.value[5].toLocaleString('pt-BR', {minimumFractionDigits: 0, maximumFractionDigits: 0});
        return [group, 'Remuneração', minimo, q1, mediana, q3, maximo].join('<br>');
     }"
   )
  ) |>
  e_title("Remuneração por Órgão")

# Renderize o gráfico atualizado
plot

```

```{r}
library(plotly)

criar_grafico_lorenz <- function(df) {
  # Criar o gráfico da curva de Lorenz
  lorenz_plot <- plot_ly(df, x = ~cumulative_prop, y = ~y_values, type ='scatter', mode ='lines', name ='Curva de Lorenz')

  # Adicionar a linha de igualdade (linha diagonal)
  lorenz_plot <- add_trace(lorenz_plot, x = c(0, 1), y = c(0, 1), type ='scatter', mode ='lines', name ='Igualdade')

  # Adicionar anotação para o índice de Gini
  lorenz_plot <- add_annotations(lorenz_plot,
                                  text = paste(
                                    "Índice de Gini:",
                                    round(unique(df$gini_index), 2)
                                  ),
                                  x = 0.2, y = 0.8,
                                  showarrow = FALSE,
                                  font = list(size = 12, color ='black'))

  # Configurar o layout do gráfico
  lorenz_plot <- layout(lorenz_plot, title ='Curva de Lorenz e Índice de Gini',
                        xaxis = list(title ='Proporção Acumulada dos Servidores Públicos'),
                        yaxis = list(title ='Proporção Acumulada da Remuneração'))

  # Exibir o gráfico
  return(lorenz_plot)
}
```


Row {.tabset}
-----------------------------------------------------------------------

### Geral

```{r}
grafico_lorenz <- criar_grafico_lorenz(df_total)
grafico_lorenz
```


### MPO 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MPO')
)
grafico_lorenz
```

### MMA 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MMA')
)
grafico_lorenz
```

### PR 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='PR')
)
grafico_lorenz
```

### ME 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='ME')
)
grafico_lorenz
```

### MCOM 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MCOM')
)
grafico_lorenz
```

### MPA 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MPA')
)
grafico_lorenz
```

### MMFDH 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MMFDH')
)
grafico_lorenz
```

### DPU 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='DPU')
)
grafico_lorenz
```

### MPI 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MPI')
)
grafico_lorenz
```

### MIDR 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MIDR')
)
grafico_lorenz
```

### MC 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MC')
)
grafico_lorenz
```

### MCID 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MCID')
)
grafico_lorenz
```

### MEC 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MEC')
)
grafico_lorenz
```

### MAPA 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MAPA')
)
grafico_lorenz
```

### MME 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MME')
)
grafico_lorenz
```

### MINC 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MINC')
)
grafico_lorenz
```

### MRE 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MRE')
)
grafico_lorenz
```

### MD 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MD')
)
grafico_lorenz
```

### MTP 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MTP')
)
grafico_lorenz
```

### MS 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MS')
)
grafico_lorenz
```

### MTUR 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MTUR')
)
grafico_lorenz
```

### MINFRA 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MINFRA')
)
grafico_lorenz
```

### MDIC 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MDIC')
)
grafico_lorenz
```

### MDA 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MDA')
)
grafico_lorenz
```

### MCTIC 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MCTIC')
)
grafico_lorenz
```

### MJ 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='MJ')
)
grafico_lorenz
```

### CGU 

```{r }
grafico_lorenz <- criar_grafico_lorenz(
  df_orgao |> filter(SG_ORGAO_VINCULACAO =='CGU')
)
grafico_lorenz
```

Página 2
==============================================================